# This workflow will install dependencies and run your Flask app
# It ensures your project builds and runs correctly by simulating the grading process

name: Flask Application Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v4
    
    # Step 2: Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies using make install
    - name: Install dependencies
      run: |
        make install

    # Step 4: Run the Flask app using make run (with sleep to give the server time to start)
    - name: Run the Flask app
      run: |
        make run &
        sleep 10
